In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("sample_dirty_dataset.csv")
df

      Name   Age  Gender   Salary Department
0    Shyam  12.0       M   3000.0         HR
1    Alice  25.0       F  50000.0         HR
2      Bob   NaN       M  60000.0         IT
3  Charlie  30.0       M      NaN    Finance
4    David  22.0       M  45000.0         IT
5      Eve  29.0       F  70000.0         HR
6    Frank  40.0    Male   8000.0        NaN
7    Grace   NaN  Female  75000.0    Finance
8    Alice  25.0       F  50000.0         HR
9      Ram  98.0       M  20000.0         HR

In [12]:
# Suppose I have Dataset
# 1 -> In tht dataset I have some missing values
# 2 -> I have to fill them 
# 3 -> Before filling them we check for outliers
#    a -> If there are outliers we firstly remove them
# 4 -> We fill the missing values
# 5 -> fill them with mean (since there are no outliers now )

In [14]:
# Remove outliers
def remove_outliers_IQR(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return data[(data[column] >= lower_bound) & (data[column] <= upper_bound)]

In [15]:
df_clean = (
    df
    .pipe(remove_outliers_IQR, column = "Age")
    .pipe(remove_outliers_IQR, column = "Salary")
)
df_clean

    Name   Age Gender   Salary Department
0  Shyam  12.0      M   3000.0         HR
1  Alice  25.0      F  50000.0         HR
4  David  22.0      M  45000.0         IT
5    Eve  29.0      F  70000.0         HR
6  Frank  40.0   Male   8000.0        NaN
8  Alice  25.0      F  50000.0         HR

In [ ]:
# What about string values
# To fill up the missing data in case of strings
# 1 -> You can either keep them unknown -> used in analysis
# 2 -> You can replace them with the maximum repeated value(mode{mo}) -> used in ML

In [17]:
# Fill the unknown values -> strings
df_clean["Department"] = df_clean["Department"].fillna("unknown")
df_clean

    Name   Age Gender   Salary Department
0  Shyam  12.0      M   3000.0         HR
1  Alice  25.0      F  50000.0         HR
4  David  22.0      M  45000.0         IT
5    Eve  29.0      F  70000.0         HR
6  Frank  40.0   Male   8000.0    unknown
8  Alice  25.0      F  50000.0         HR

In [19]:
# Remove duplicates
df_clean.drop_duplicates(inplace = True)
df_clean

    Name   Age Gender   Salary Department
0  Shyam  12.0      M   3000.0         HR
1  Alice  25.0      F  50000.0         HR
4  David  22.0      M  45000.0         IT
5    Eve  29.0      F  70000.0         HR
6  Frank  40.0   Male   8000.0    unknown

In [20]:
# Making Data consistent
df_clean["Gender"] = df["Gender"].replace({
    "Male" : "M",
    "Female" : "F"
})
df_clean

    Name   Age Gender   Salary Department
0  Shyam  12.0      M   3000.0         HR
1  Alice  25.0      F  50000.0         HR
4  David  22.0      M  45000.0         IT
5    Eve  29.0      F  70000.0         HR
6  Frank  40.0      M   8000.0    unknown

In [22]:
df_clean.to_csv("Cleaned_data.csv", index = False)
df_clean

    Name   Age Gender   Salary Department
0  Shyam  12.0      M   3000.0         HR
1  Alice  25.0      F  50000.0         HR
4  David  22.0      M  45000.0         IT
5    Eve  29.0      F  70000.0         HR
6  Frank  40.0      M   8000.0    unknown